# doc_structure_version: 3.0

# === rules configuration ===
rules:
  root_dirs:
    - docs/rules/
  doc_types_map:
    docs/rules/: rule
  patterns:
    target_glob: "**/*.md"
    exclude: []

# === specs configuration ===
specs:
  root_dirs:
    - "docs/specs/**/requirements/"
    - "docs/specs/**/design/"
    - "docs/specs/**/plan/"
  doc_types_map:
    "docs/specs/**/requirements/": requirement
    "docs/specs/**/design/": design
    "docs/specs/**/plan/": plan
  patterns:
    target_glob: "**/*.md"
    exclude: []
